def preguntas():
    pregunta1=["Cual es la abreviatura de kilometro","A: kl","B: klm","C: km","D: kmt",3,"imagenes/pregunta1.ogg"]
    pregunta2=["Quien salio de la lampara de Aladino","A: Un genio","B: Un principe","C: Una bruja","D: Un sapo",1,"imagenes/pregunta2.ogg"]
    pregunta3=["La antena de radio sirve para","A: Adornar el radio","B: Mejorar la senial","C: Regular la corriente","D: Eliminar el ruido",2,"imagenes/pregunta3.ogg"]
    pregunta4=["Cual es el simbolo quimico del aluminio","A: Ao","B: Am","C: Lm","D: Al",4,"imagenes/pregunta4.ogg"]
    pregunta5=["Las gotas heladas que caen en algunas tormentas se les llama","A: Granizo","B: Nieve","C: Lluvia","D: Rocio",1,"imagenes/pregunta5.ogg"]
    pregunta6=["De que color es una senial de Pare","A: verde y azul","B: rojo y blanco","C: amarillo y negro","D: rosa y verde",2,"imagenes/pregunta6.ogg"]
    pregunta7=["Cual de estos animales es un reptil","A: Cocodrilos","B: Serpientes","C: Lagartos","D: Todos",4,"imagenes/pregunta7.ogg"]
    pregunta8=["Cual de estas piedras es de color verde","A: Rubi","B: Topacio","C: Zafiro","D: Esmaraldas",4,"imagenes/pregunta8.ogg"]
    pregunta9=["Para que el pan se fermente o crezca debe llevar","A: Levadura","B: Agua","C: Uvas","D: Amor",1,"imagenes/pregunta9.ogg"]
    pregunta10=["Este perro es el mas alto de todos ellos. Tiene un pelaje delgado.","A: Lobero Irlandes","B: Gran danes","C: Deerhound Escoces","D: San Bernardo",1,"imagenes/pregunta10.ogg"]
    pregunta11=["El protagonita de este espectaculo tiene un abuelo llamado Lou","A: Los padrinos magicos","B: Doug","C: Rugrats","D: Clarissa lo explica todo",3,"imagenes/pregunta11.ogg"]
    pregunta12=["Cual es el continente mas grande del mundo","A: Asia","B: Europa","C: Africa","D: America",1,"imagenes/pregunta12.ogg"]
    pregunta13=["Cual es la forma completa de la abreviatura GMT","A: Greenwich Mean Time","B: Greenland Mean time","C: German Mean Time","D: Gippsland Mean Time",1,"imagenes/pregunta13.ogg"]
    pregunta14=["Cual es el oceano en el que llega el caudal del rio amazonas","A: El Artico","B: El indio","C: El Atlantico","D: El Pacifico",3,"imagenes/pregunta14.ogg"]
    pregunta15=["Cual es el aparato que facilita la refrigeracion en una nevera","A: Congelador","B: Barillas metalicas","C: Tener la puerta cerrada","D: Compresor",4,"imagenes/pregunta15.ogg"]
    pregunta16=["Cuantos jugadores conforman un equipo de voleibol en la cancha","A: 10","B: 5","C: 6","D: 4",3,"imagenes/pregunta16.ogg"]
    pregunta17=["En matematicas, diez milimetros son...","A: Un poquito","B: Un metro","C: Un decimetro","D: Un centimetro",4,"imagenes/pregunta17.ogg"]
    pregunta18=["Cuantos segundos tiene un minuto y medio","A: 45","B: 90","C: 60","D: 75",2,"imagenes/pregunta18.ogg"]
    pregunta19=["Los delfines son animales de sangre...","A: Caliente","B: Fria","C: Azul","D: Gris",1,"imagenes/pregunta19.ogg"]
    lista=[pregunta1,pregunta2,pregunta3,pregunta4,pregunta5,pregunta6,pregunta7,pregunta8,pregunta9,pregunta10,pregunta11,pregunta12,pregunta13,pregunta14,pregunta15,pregunta16,pregunta17,pregunta18,pregunta19]
    return lista